#!/bin/bash

if [[ ! -e "$(dirname $0)/bin/signapp.tgz" ]]; then
    echo -e "\e[31mMissing binary. Please do a distribution build first.\e[0m"
    exit 1
fi

pushd $(dirname $0) > /dev/null
TOOLS_DIR=$(pwd)
BUILD_DIR=$TOOLS_DIR/..
popd > /dev/null
CURR_DIR=$(pwd)

DOCKER_IMAGE=hsm2:runtime

echo -e "\e[96mBuilding docker image $DOCKER_IMAGE (this could take a few minutes)..."
docker build -q -t $DOCKER_IMAGE $TOOLS_DIR
echo -e "\e[96mDocker image build done.\e[0m"
echo

# Expand signapp.tgz
rm -rf $TOOLS_DIR/bin/signapp
mkdir -p $TOOLS_DIR/bin/signapp
tar -xzmf $TOOLS_DIR/bin/signapp.tgz -C $TOOLS_DIR/bin/signapp

docker run -t --rm -v $BUILD_DIR:/build -v $CURR_DIR:/work -v /dev/bus/usb:/dev/bus/usb --privileged -w /work $DOCKER_IMAGE /build/tools/bin/signapp/signapp $@

# Cleanup signapp.tgz
rm -rf $TOOLS_DIR/bin/signapp
